import {expect,it} from 'vitest';
import {gammaParameters,gammaEmitterMask} from '../../src/picker/render/gamma';
import type {SceneFrame} from '../../src/picker/types';
function frame(width=16,height=8):SceneFrame {
 const zero={area:0,centroid:.5,spread:0};
 return {revision:7,seed:236,time:0,source:{width,height,rgba:new Uint8ClampedArray(width*height*4).fill(128)},layers:[{materialId:'one',mask:new Float32Array(width*height).fill(1),deltaOklab:[0,0,0],appearance:{visibleLinear:[.3,.3,.3],emissionLinear:[0,0,0],bands:{gamma:zero,xray:zero,uv:zero,visible:zero,infrared:zero,microwave:zero,radio:zero}}}]};
}
import {composeBase} from '../../src/picker/render/cpu';
it('gamma parameters obey area/centroid/time contracts',()=>{expect(gammaParameters({area:.5,centroid:1,spread:0},42,.26)).toEqual({hitRate:.03,displacementPx:6,contourCount:32,tick:3});});
it('zero gamma is identity and fixed frozen time is repeatable',()=>{const f=frame();expect(gammaEmitterMask(f).every(v=>v===0)).toBe(true);expect(gammaEmitterMask(f)).toEqual(gammaEmitterMask(f));});
it('stronger gamma includes weaker events and respects masks',()=>{const f=frame(64,64),weak={...f,layers:[{...f.layers[0],appearance:{...f.layers[0].appearance,bands:{...f.layers[0].appearance.bands,gamma:{area:.2,centroid:.5,spread:0}}}}]};const strong={...weak,layers:[{...weak.layers[0],appearance:{...weak.layers[0].appearance,bands:{...weak.layers[0].appearance.bands,gamma:{area:1,centroid:.5,spread:0}}}}]};const a=gammaEmitterMask(weak),b=gammaEmitterMask(strong);expect(a.some(v=>v>0)).toBe(true);for(let i=0;i<a.length;i++)if(a[i]>0)expect(b[i]).toBeGreaterThanOrEqual(a[i]);expect(gammaEmitterMask({...strong,layers:[{...strong.layers[0],mask:new Float32Array(4096)}]}).every(v=>v===0)).toBe(true);});
it('gamma distortion stays inside its material mask and frozen composition repeats',()=>{const f=frame(64,64),mask=new Float32Array(4096);for(let y=0;y<64;y++)for(let x=0;x<32;x++)mask[y*64+x]=1;const active={...f,layers:[{...f.layers[0],mask,appearance:{...f.layers[0].appearance,bands:{...f.layers[0].appearance.bands,gamma:{area:1,centroid:.2,spread:.1}}}}]};const base=composeBase(f),result=composeBase(active);expect(result).toEqual(composeBase(active));for(let i=0;i<mask.length;i++)if(mask[i]===0)for(let c=0;c<4;c++)expect(result[i*4+c]).toBe(base[i*4+c]);expect(result.some((v,i)=>v!==base[i])).toBe(true);});
it('gamma tearing samples the isolated treated material rather than reverting infrared',()=>{const f=frame(64,64),infrared={...f,layers:[{...f.layers[0],appearance:{...f.layers[0].appearance,bands:{...f.layers[0].appearance.bands,infrared:{area:1,centroid:1,spread:0}}}}]},gamma={...infrared,layers:[{...infrared.layers[0],appearance:{...infrared.layers[0].appearance,bands:{...infrared.layers[0].appearance.bands,gamma:{area:1,centroid:.5,spread:0}}}}]};const treated=composeBase(infrared),disturbed=composeBase(gamma);for(let i=0;i<treated.length;i++)expect(disturbed[i]).toBeGreaterThanOrEqual(treated[i]-1e-6);});
