import {expect,it} from 'vitest';
import {composeBase,renderCpu} from '../../src/picker/render/cpu';
import type {SceneFrame} from '../../src/picker/types';
function frame(width=16,height=8):SceneFrame {
 const zero={area:0,centroid:.5,spread:0};
 return {revision:7,seed:236,time:0,source:{width,height,rgba:new Uint8ClampedArray(width*height*4).fill(128)},layers:[{materialId:'one',mask:new Float32Array(width*height).fill(1),deltaOklab:[0,0,0],appearance:{visibleLinear:[.3,.3,.3],emissionLinear:[0,0,0],bands:{gamma:zero,xray:zero,uv:zero,visible:zero,infrared:zero,microwave:zero,radio:zero}}}]};
}
import {createRenderer} from '../../src/picker/render/gpu';
it('no changes reproduce source bytes including semitransparent alpha',()=>{const f=frame();expect(renderCpu(f).rgba).toEqual(f.source.rgba);});
it('IR position changes hue while area changes strength',()=>{const f=frame();const apply=(area:number,centroid:number)=>renderCpu({...f,layers:[{...f.layers[0],appearance:{...f.layers[0].appearance,bands:{...f.layers[0].appearance.bands,infrared:{area,centroid,spread:0}}}}]}).rgba;expect(apply(0,.2)).toEqual(f.source.rgba);expect(apply(1,0)).not.toEqual(apply(1,1));expect(apply(.2,.5)).not.toEqual(apply(.8,.5));});
it('cached estimated depth supplies X-ray slices',()=>{const f=frame();const depth={imageHash:'a',modelHash:'b',width:16,height:8,values:new Float32Array(128).fill(.5)};const apply=(centroid:number)=>renderCpu({...f,depth,layers:[{...f.layers[0],appearance:{...f.layers[0].appearance,bands:{...f.layers[0].appearance.bands,xray:{area:1,centroid,spread:0}}}}]}).rgba;expect(apply(.5)[0]).toBeGreaterThan(apply(0)[0]);});
it('adapter failure preserves CPU editing and capture revision without claiming cascades',async()=>{const messages:string[]=[];const canvas={width:0,height:0,getContext:()=>({putImageData:()=>{}})} as unknown as HTMLCanvasElement;const renderer=await createRenderer(canvas,{onStatus:m=>messages.push(m)});expect(renderer.mode).toBe('cpu');const old=frame(),dirty={...old,revision:8};const captures=await Promise.all([renderer.capture(old),renderer.capture(dirty)]);expect(captures.map(c=>c.revision)).toEqual([7,8]);expect(messages.join(' ')).toMatch(/reduced.*bloom/i);await renderer.dispose();await expect(renderer.capture(dirty)).rejects.toThrow(/disposed/i);});
it('quiet radio and microwave overlays preserve alpha and stay below 0.15 blend opacity',()=>{const f=frame(64,64),base=composeBase(f),active={...f,layers:[{...f.layers[0],appearance:{...f.layers[0].appearance,bands:{...f.layers[0].appearance.bands,radio:{area:1,centroid:.2,spread:0},microwave:{area:1,centroid:.8,spread:0}}}}]};const result=composeBase(active);let changed=false;for(let i=0;i<64*64;i++){expect(result[i*4+3]).toBe(base[i*4+3]);for(let c=0;c<3;c++){const target=c===2?.65:.3;expect(Math.abs(result[i*4+c]-base[i*4+c])).toBeLessThanOrEqual(Math.abs(target-base[i*4+c])*.15+1e-6);if(result[i*4+c]!==base[i*4+c])changed=true;}}expect(changed).toBe(true);});
